//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S01002 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S01002() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("semigura.Resources.S01002", typeof(S01002).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 福井酒造.
        /// </summary>
        public static string F_001 {
            get {
                return ResourceManager.GetString("F_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 福井酒造2.
        /// </summary>
        public static string F_002 {
            get {
                return ResourceManager.GetString("F_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファクトリー.
        /// </summary>
        public static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション.
        /// </summary>
        public static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーとパスワードが正しくない。.
        /// </summary>
        public static string msg_login_fail {
            get {
                return ResourceManager.GetString("msg_login_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to もろみ工程.
        /// </summary>
        public static string PROCESS_1 {
            get {
                return ResourceManager.GetString("PROCESS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麹工程.
        /// </summary>
        public static string PROCESS_2 {
            get {
                return ResourceManager.GetString("PROCESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規登録.
        /// </summary>
        public static string regist {
            get {
                return ResourceManager.GetString("regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインID、パスワードを記憶する。.
        /// </summary>
        public static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション.
        /// </summary>
        public static string ROOM {
            get {
                return ResourceManager.GetString("ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数.
        /// </summary>
        public static string TH_1 {
            get {
                return ResourceManager.GetString("TH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンクNo..
        /// </summary>
        public static string TH_1_1 {
            get {
                return ResourceManager.GetString("TH_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 米蓋No..
        /// </summary>
        public static string TH_1_2 {
            get {
                return ResourceManager.GetString("TH_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク.
        /// </summary>
        public static string TH_2 {
            get {
                return ResourceManager.GetString("TH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to センサー／温度.
        /// </summary>
        public static string TH_3 {
            get {
                return ResourceManager.GetString("TH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインID.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
