//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S02001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S02001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("semigura.Resources.S02001", typeof(S02001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 酸.
        /// </summary>
        public static string acid {
            get {
                return ResourceManager.GetString("acid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アルコール分.
        /// </summary>
        public static string alcohol {
            get {
                return ResourceManager.GetString("alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アミノ酸.
        /// </summary>
        public static string amomiAcid {
            get {
                return ResourceManager.GetString("amomiAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品温.
        /// </summary>
        public static string avgTempCol {
            get {
                return ResourceManager.GetString("avgTempCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string backBtn {
            get {
                return ResourceManager.GetString("backBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボーメ度（比重).
        /// </summary>
        public static string baume1 {
            get {
                return ResourceManager.GetString("baume1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボーメ.
        /// </summary>
        public static string baume2 {
            get {
                return ResourceManager.GetString("baume2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが変更されました。 保存しますか？.
        /// </summary>
        public static string cfm_SaveEdit {
            get {
                return ResourceManager.GetString("cfm_SaveEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月日.
        /// </summary>
        public static string dateCol {
            get {
                return ResourceManager.GetString("dateCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計測日.
        /// </summary>
        public static string dateTime {
            get {
                return ResourceManager.GetString("dateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to どちらか1つ.
        /// </summary>
        public static string dochira {
            get {
                return ResourceManager.GetString("dochira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計測日は仕込号数の開始日以降である必要があります。(開始日：{0}).
        /// </summary>
        public static string entryErrorMsg {
            get {
                return ResourceManager.GetString("entryErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 測定日は現在の日付より前である必要があります。.
        /// </summary>
        public static string entryErrorMsgDay {
            get {
                return ResourceManager.GetString("entryErrorMsgDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファクトリー.
        /// </summary>
        public static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グルーコス.
        /// </summary>
        public static string glucose {
            get {
                return ResourceManager.GetString("glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写真.
        /// </summary>
        public static string imageLabel {
            get {
                return ResourceManager.GetString("imageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ入力画面へ.
        /// </summary>
        public static string inputData {
            get {
                return ResourceManager.GetString("inputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数.
        /// </summary>
        public static string lot {
            get {
                return ResourceManager.GetString("lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用中.
        /// </summary>
        public static string lotStatus {
            get {
                return ResourceManager.GetString("lotStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除してもよろしいですか？.
        /// </summary>
        public static string msg_delete_confirm {
            get {
                return ResourceManager.GetString("msg_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常に登録されました.
        /// </summary>
        public static string msg_regist_completed {
            get {
                return ResourceManager.GetString("msg_regist_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本酒.
        /// </summary>
        public static string nihonsyu {
            get {
                return ResourceManager.GetString("nihonsyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日順.
        /// </summary>
        public static string noCol {
            get {
                return ResourceManager.GetString("noCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室：湿度.
        /// </summary>
        public static string roomHumi {
            get {
                return ResourceManager.GetString("roomHumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室：温度.
        /// </summary>
        public static string roomTemp {
            get {
                return ResourceManager.GetString("roomTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク.
        /// </summary>
        public static string tank {
            get {
                return ResourceManager.GetString("tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均品温.
        /// </summary>
        public static string tempAvg {
            get {
                return ResourceManager.GetString("tempAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品温（下）.
        /// </summary>
        public static string TempBot {
            get {
                return ResourceManager.GetString("TempBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品温（中）.
        /// </summary>
        public static string TempMid {
            get {
                return ResourceManager.GetString("TempMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 温度.
        /// </summary>
        public static string tempRoomCol {
            get {
                return ResourceManager.GetString("tempRoomCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品温（上）.
        /// </summary>
        public static string TempTop {
            get {
                return ResourceManager.GetString("TempTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時点.
        /// </summary>
        public static string timePoint {
            get {
                return ResourceManager.GetString("timePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 度.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年/月/日 時間 .
        /// </summary>
        public static string yearMD {
            get {
                return ResourceManager.GetString("yearMD", resourceCulture);
            }
        }
    }
}
