//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S03002 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S03002() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("semigura.Resources.S03002", typeof(S03002).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容積(l).
        /// </summary>
        public static string capacity {
            get {
                return ResourceManager.GetString("capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了日.
        /// </summary>
        public static string enddate {
            get {
                return ResourceManager.GetString("enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファクトリー.
        /// </summary>
        public static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高度.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用中.
        /// </summary>
        public static string inuse {
            get {
                return ResourceManager.GetString("inuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数.
        /// </summary>
        public static string lot {
            get {
                return ResourceManager.GetString("lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高温度.
        /// </summary>
        public static string maxt {
            get {
                return ResourceManager.GetString("maxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低気温.
        /// </summary>
        public static string mint {
            get {
                return ResourceManager.GetString("mint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除してもよろしいですか？.
        /// </summary>
        public static string msg_delete_confirm {
            get {
                return ResourceManager.GetString("msg_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテムが存在しています。({0}:{1}).
        /// </summary>
        public static string msg_item_exist {
            get {
                return ResourceManager.GetString("msg_item_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 米類.
        /// </summary>
        public static string rice {
            get {
                return ResourceManager.GetString("rice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string rowno {
            get {
                return ResourceManager.GetString("rowno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string searchbtn {
            get {
                return ResourceManager.GetString("searchbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始日.
        /// </summary>
        public static string startdate {
            get {
                return ResourceManager.GetString("startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンクコード.
        /// </summary>
        public static string tankcode {
            get {
                return ResourceManager.GetString("tankcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水量確認.
        /// </summary>
        public static string watervolume {
            get {
                return ResourceManager.GetString("watervolume", resourceCulture);
            }
        }
    }
}
