//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S03005 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S03005() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("semigura.Resources.S03005", typeof(S03005).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string backbtn {
            get {
                return ResourceManager.GetString("backbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クローズ.
        /// </summary>
        public static string closebtn {
            get {
                return ResourceManager.GetString("closebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク.
        /// </summary>
        public static string containerid {
            get {
                return ResourceManager.GetString("containerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンテキスト.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成日.
        /// </summary>
        public static string created_on {
            get {
                return ResourceManager.GetString("created_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string dialog_confirm_cancelbtn {
            get {
                return ResourceManager.GetString("dialog_confirm_cancelbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string dialog_confirm_okbtn {
            get {
                return ResourceManager.GetString("dialog_confirm_okbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        public static string dialog_confirm_title {
            get {
                return ResourceManager.GetString("dialog_confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファクトリー.
        /// </summary>
        public static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緊急.
        /// </summary>
        public static string level_emergency {
            get {
                return ResourceManager.GetString("level_emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string level_warning {
            get {
                return ResourceManager.GetString("level_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数.
        /// </summary>
        public static string lot {
            get {
                return ResourceManager.GetString("lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クローズしますか？.
        /// </summary>
        public static string msg_close_confirm {
            get {
                return ResourceManager.GetString("msg_close_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除してもよろしいですか？.
        /// </summary>
        public static string msg_delete_confirm {
            get {
                return ResourceManager.GetString("msg_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテムが存在しています。({0}:{1}).
        /// </summary>
        public static string msg_item_exist {
            get {
                return ResourceManager.GetString("msg_item_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者.
        /// </summary>
        public static string person_incharge {
            get {
                return ResourceManager.GetString("person_incharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低気温：{0}°C　最高気温：{1}°C　品温：{2}°C　(センサー名：{3}).
        /// </summary>
        public static string process_alert_content_seigiku {
            get {
                return ResourceManager.GetString("process_alert_content_seigiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低気温：{0}°C　最高気温：{1}°C　品温：{2}°C　(タンク：{3}).
        /// </summary>
        public static string process_alert_content_tank {
            get {
                return ResourceManager.GetString("process_alert_content_tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}]品温が許容温度を超えています。({1}：{2}).
        /// </summary>
        public static string process_alert_title {
            get {
                return ResourceManager.GetString("process_alert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to もろみ.
        /// </summary>
        public static string process_moromi {
            get {
                return ResourceManager.GetString("process_moromi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麹.
        /// </summary>
        public static string process_seigiku {
            get {
                return ResourceManager.GetString("process_seigiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string rowno {
            get {
                return ResourceManager.GetString("rowno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string savebtn {
            get {
                return ResourceManager.GetString("savebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string searchbtn {
            get {
                return ResourceManager.GetString("searchbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クローズ.
        /// </summary>
        public static string status_closed {
            get {
                return ResourceManager.GetString("status_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オープン.
        /// </summary>
        public static string status_open {
            get {
                return ResourceManager.GetString("status_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 処理中.
        /// </summary>
        public static string status_processing {
            get {
                return ResourceManager.GetString("status_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択してください.
        /// </summary>
        public static string status_title {
            get {
                return ResourceManager.GetString("status_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトル.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイプ.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麹.
        /// </summary>
        public static string type_seigiku {
            get {
                return ResourceManager.GetString("type_seigiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク.
        /// </summary>
        public static string type_tank {
            get {
                return ResourceManager.GetString("type_tank", resourceCulture);
            }
        }
    }
}
