//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S03001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S03001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("semigura.Resources.S03001", typeof(S03001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string adbtn {
            get {
                return ResourceManager.GetString("adbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string backbtn {
            get {
                return ResourceManager.GetString("backbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了.
        /// </summary>
        public static string btn_finish {
            get {
                return ResourceManager.GetString("btn_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始.
        /// </summary>
        public static string btn_start {
            get {
                return ResourceManager.GetString("btn_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容積(l).
        /// </summary>
        public static string capacity {
            get {
                return ResourceManager.GetString("capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数を終了してもよろしいですか？.
        /// </summary>
        public static string cfm_enddatelot {
            get {
                return ResourceManager.GetString("cfm_enddatelot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to には未使用のタンクとセンサーがあります。仕込号数を終了してもよろしいですか？.
        /// </summary>
        public static string cfr_end_otherlot {
            get {
                return ResourceManager.GetString("cfr_end_otherlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了してもよろしいですか？.
        /// </summary>
        public static string cfrm_endlotcontainer {
            get {
                return ResourceManager.GetString("cfrm_endlotcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク/センサー.
        /// </summary>
        public static string classify {
            get {
                return ResourceManager.GetString("classify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了日.
        /// </summary>
        public static string enddate {
            get {
                return ResourceManager.GetString("enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了日（仕込号数）.
        /// </summary>
        public static string enddatelot {
            get {
                return ResourceManager.GetString("enddatelot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特上.
        /// </summary>
        public static string extra_special {
            get {
                return ResourceManager.GetString("extra_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファクトリー.
        /// </summary>
        public static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一等.
        /// </summary>
        public static string first_class {
            get {
                return ResourceManager.GetString("first_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高度.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用中.
        /// </summary>
        public static string inuse {
            get {
                return ResourceManager.GetString("inuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区分.
        /// </summary>
        public static string kubun {
            get {
                return ResourceManager.GetString("kubun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麴用ロケーション.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数.
        /// </summary>
        public static string lot {
            get {
                return ResourceManager.GetString("lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数.
        /// </summary>
        public static string lotcode {
            get {
                return ResourceManager.GetString("lotcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高温度.
        /// </summary>
        public static string maxt {
            get {
                return ResourceManager.GetString("maxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to を入力してください。.
        /// </summary>
        public static string messege {
            get {
                return ResourceManager.GetString("messege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低温度.
        /// </summary>
        public static string mint {
            get {
                return ResourceManager.GetString("mint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to もろみ.
        /// </summary>
        public static string moromi {
            get {
                return ResourceManager.GetString("moromi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンクまたはセンサーを追加してください。.
        /// </summary>
        public static string msg_add_tanksensor {
            get {
                return ResourceManager.GetString("msg_add_tanksensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to の最大値と最小値を確認してください。.
        /// </summary>
        public static string msg_checkminmax {
            get {
                return ResourceManager.GetString("msg_checkminmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了日と開始日を確認してください。.
        /// </summary>
        public static string msg_chk_startenddate {
            get {
                return ResourceManager.GetString("msg_chk_startenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除してもよろしいですか？.
        /// </summary>
        public static string msg_delete_confirm {
            get {
                return ResourceManager.GetString("msg_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数が使用中ですので、削除する前に終了してください.
        /// </summary>
        public static string msg_detele_using {
            get {
                return ResourceManager.GetString("msg_detele_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to が複製されています。.
        /// </summary>
        public static string msg_duplicate {
            get {
                return ResourceManager.GetString("msg_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテムが存在しています。({0}:{1}).
        /// </summary>
        public static string msg_item_exist {
            get {
                return ResourceManager.GetString("msg_item_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to センサーリストに未選択のアイテムがあります。ご選択ください。.
        /// </summary>
        public static string msg_sensor_empty {
            get {
                return ResourceManager.GetString("msg_sensor_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンクリストに未選択のアイテムがあります。ご選択ください。.
        /// </summary>
        public static string msg_tank_empty {
            get {
                return ResourceManager.GetString("msg_tank_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}で使用されています。.
        /// </summary>
        public static string msg_using {
            get {
                return ResourceManager.GetString("msg_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 米類.
        /// </summary>
        public static string rice {
            get {
                return ResourceManager.GetString("rice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string rowno {
            get {
                return ResourceManager.GetString("rowno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string savebtn {
            get {
                return ResourceManager.GetString("savebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string searchbtn {
            get {
                return ResourceManager.GetString("searchbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二等.
        /// </summary>
        public static string second_class {
            get {
                return ResourceManager.GetString("second_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麴.
        /// </summary>
        public static string seigiku {
            get {
                return ResourceManager.GetString("seigiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精米歩合.
        /// </summary>
        public static string seimaibuai {
            get {
                return ResourceManager.GetString("seimaibuai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麴用センサー.
        /// </summary>
        public static string sensor {
            get {
                return ResourceManager.GetString("sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to センサー.
        /// </summary>
        public static string sensortype {
            get {
                return ResourceManager.GetString("sensortype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特等.
        /// </summary>
        public static string special_class {
            get {
                return ResourceManager.GetString("special_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始日.
        /// </summary>
        public static string startdate {
            get {
                return ResourceManager.GetString("startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始日（仕込号数）.
        /// </summary>
        public static string startdatelot {
            get {
                return ResourceManager.GetString("startdatelot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク.
        /// </summary>
        public static string tank {
            get {
                return ResourceManager.GetString("tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三等.
        /// </summary>
        public static string third_class {
            get {
                return ResourceManager.GetString("third_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイプ.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
    }
}
