//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S09001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S09001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("semigura.Resources.S09001", typeof(S09001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string addbtn {
            get {
                return ResourceManager.GetString("addbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string backbtn {
            get {
                return ResourceManager.GetString("backbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 材料.
        /// </summary>
        public static string material {
            get {
                return ResourceManager.GetString("material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除してもよろしいですか？.
        /// </summary>
        public static string msg_delete_confirm {
            get {
                return ResourceManager.GetString("msg_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテムが存在しています。({0}：{1}).
        /// </summary>
        public static string msg_item_exist {
            get {
                return ResourceManager.GetString("msg_item_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程が重複しています。.
        /// </summary>
        public static string msg_validation_duplicate {
            get {
                return ResourceManager.GetString("msg_validation_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の値は{1}より小さくなければなりません。.
        /// </summary>
        public static string msg_validation_min_max {
            get {
                return ResourceManager.GetString("msg_validation_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パーセンテージ値は0〜100の間である必要があります。.
        /// </summary>
        public static string msg_validation_percent {
            get {
                return ResourceManager.GetString("msg_validation_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 備考.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精米歩合.
        /// </summary>
        public static string rice_polishing_ratio {
            get {
                return ResourceManager.GetString("rice_polishing_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精米歩合名.
        /// </summary>
        public static string rice_polishing_ratio_name {
            get {
                return ResourceManager.GetString("rice_polishing_ratio_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 純米大吟醸.
        /// </summary>
        public static string rice_polishing_ratio_type1 {
            get {
                return ResourceManager.GetString("rice_polishing_ratio_type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 純米吟醸.
        /// </summary>
        public static string rice_polishing_ratio_type2 {
            get {
                return ResourceManager.GetString("rice_polishing_ratio_type2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 純米酒.
        /// </summary>
        public static string rice_polishing_ratio_type3 {
            get {
                return ResourceManager.GetString("rice_polishing_ratio_type3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本醸造.
        /// </summary>
        public static string rice_polishing_ratio_type4 {
            get {
                return ResourceManager.GetString("rice_polishing_ratio_type4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他.
        /// </summary>
        public static string rice_polishing_ratio_type99 {
            get {
                return ResourceManager.GetString("rice_polishing_ratio_type99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精米歩合値.
        /// </summary>
        public static string rice_polishing_ratio_value {
            get {
                return ResourceManager.GetString("rice_polishing_ratio_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string rowno {
            get {
                return ResourceManager.GetString("rowno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string savebtn {
            get {
                return ResourceManager.GetString("savebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string searchbtn {
            get {
                return ResourceManager.GetString("searchbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高品温.
        /// </summary>
        public static string temp_max {
            get {
                return ResourceManager.GetString("temp_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低品温.
        /// </summary>
        public static string temp_min {
            get {
                return ResourceManager.GetString("temp_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション.
        /// </summary>
        public static string type_location {
            get {
                return ResourceManager.GetString("type_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麹.
        /// </summary>
        public static string type_seigiku {
            get {
                return ResourceManager.GetString("type_seigiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク.
        /// </summary>
        public static string type_tank {
            get {
                return ResourceManager.GetString("type_tank", resourceCulture);
            }
        }
    }
}
