//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S09004 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S09004() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("semigura.Resources.S09004", typeof(S09004).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string adbtn {
            get {
                return ResourceManager.GetString("adbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string backbtn {
            get {
                return ResourceManager.GetString("backbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファクトリー.
        /// </summary>
        public static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインID.
        /// </summary>
        public static string login_id {
            get {
                return ResourceManager.GetString("login_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仕込号数.
        /// </summary>
        public static string lot {
            get {
                return ResourceManager.GetString("lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除してもよろしいですか？.
        /// </summary>
        public static string msg_delete_confirm {
            get {
                return ResourceManager.GetString("msg_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテムが存在しています。({0}:{1}、{2}: {3}).
        /// </summary>
        public static string msg_item_exist {
            get {
                return ResourceManager.GetString("msg_item_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端末が 仕込号数({0})で使われていますので、削除ができません。.
        /// </summary>
        public static string msg_terminal_using {
            get {
                return ResourceManager.GetString("msg_terminal_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端末が 仕込号数({0})で使われていますので、端末のタイプを変更することが出来ません。.
        /// </summary>
        public static string msg_terminal_using_cannot_change_type {
            get {
                return ResourceManager.GetString("msg_terminal_using_cannot_change_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未使用.
        /// </summary>
        public static string not_used {
            get {
                return ResourceManager.GetString("not_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string rowno {
            get {
                return ResourceManager.GetString("rowno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string savebtn {
            get {
                return ResourceManager.GetString("savebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string searchbtn {
            get {
                return ResourceManager.GetString("searchbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク.
        /// </summary>
        public static string tank {
            get {
                return ResourceManager.GetString("tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端末コード.
        /// </summary>
        public static string terminal_code {
            get {
                return ResourceManager.GetString("terminal_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端末名.
        /// </summary>
        public static string terminal_name {
            get {
                return ResourceManager.GetString("terminal_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイプ.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カメラ.
        /// </summary>
        public static string type_camera {
            get {
                return ResourceManager.GetString("type_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケーション用センサー.
        /// </summary>
        public static string type_location {
            get {
                return ResourceManager.GetString("type_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製麴用センサー.
        /// </summary>
        public static string type_seigiku {
            get {
                return ResourceManager.GetString("type_seigiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タンク用センサー.
        /// </summary>
        public static string type_tank {
            get {
                return ResourceManager.GetString("type_tank", resourceCulture);
            }
        }
    }
}
