//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Models;
using semigura.Models;

namespace semigura.DBContext.Entities
{

    public partial class DBEntities : DbContext
    {
        public DBEntities()
        {
        }
        public DBEntities(DbContextOptions options) : base(options)
        {
            AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }

        public virtual DbSet<AlertMail> AlertMail { get; set; }
        public virtual DbSet<Container> Container { get; set; }
        public virtual DbSet<DataEntry> DataEntry { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupRole> GroupRole { get; set; }
        public virtual DbSet<GroupUser> GroupUser { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Lot> Lot { get; set; }
        public virtual DbSet<LotContainer> LotContainer { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialStandVal> MaterialStandVal { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleResource> RoleResource { get; set; }
        public virtual DbSet<SensorData> SensorData { get; set; }
        public virtual DbSet<Terminal> Terminal { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<CapacityRefer> CapacityRefer { get; set; }
        public virtual DbSet<LotContainerTerminal> LotContainerTerminal { get; set; }

        public DbSet<User> Users => Set<User>();
        public DbSet<Message> Messages => Set<Message>();
        public DbSet<MyFile> MyFiles => Set<MyFile>();
        public DbSet<Sensor> Sensors => base.Set<Sensor>();
    }
}
