//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.DBContext.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Factory")]
    public partial class Factory
    {
        [Column(TypeName ="char(32)")]
        public string Id { get; set; }
        [MaxLength(100)]
        public string Code { get; set; }
        [MaxLength(250)]
        public string Name { get; set; }
        [MaxLength(100)]
        public string Phone { get; set; }
        [MaxLength(500)]
        public string Address { get; set; }
        [MaxLength(2)]
        public string CountryCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Column(TypeName = "char(32)")]
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Column(TypeName = "char(32)")]
        public string ModifiedById { get; set; }
    }
}
