using semigura.Commons;
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.DBContext.Models
{
    public partial class LotContainerModel
    {
        public int No { get; set; }
        public string Id { get; set; }
        public string TankId { get; set; }
        public string TankCode { get; set; }
        public string FactoryId { get; set; }
        public string FactoryName { get; set; }
        public string LotId { get; set; }
        public string LotCode { get; set; }
        public string LocationId { get; set; }
        public string LocationName { get; set; }
        public string ContainerId { get; set; }
        public string LocationCode { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedById { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartDateUnixTimeStamp
        {
            get
            {
                return StartDate.HasValue ? Utils.DateTimeToLongTimeString(StartDate) : null;
            }
        }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndDateUnixTimeStamp
        {
            get
            {
                return EndDate.HasValue ? Utils.DateTimeToLongTimeString(EndDate) : null;
            }
        }

        public Nullable<System.DateTime> StartDateLot { get; set; }
        public string StartDateLotUnixTimeStamp
        {
            get
            {
                return StartDateLot.HasValue ? Utils.DateTimeToLongTimeString(StartDateLot) : null;
            }
        }

        public Nullable<System.DateTime> EndDateLot { get; set; }

        public string EndDateLotUnixTimeStamp
        {
            get
            {
                return EndDateLot.HasValue ? Utils.DateTimeToLongTimeString(EndDateLot) : null;
            }
        }

        public string Rice { get; set; }

        public Nullable<int> Kubun { get; set; }

        public string KubunName { get; set; }

        public string Seimaibuai { get; set; }

        public Nullable<decimal> RiceRatio { get; set; }

        public Nullable<int> Type { get; set; }
        public Nullable<decimal> TempMin { get; set; }
        public Nullable<decimal> TempMax { get; set; }

        public string Note { get; set; }
        public string TerminalId { get; set; }
        public string TerminalCode { get; set; }
        public string TerminalName { get; set; }
        public int ContainerType { get; set; }
        public Nullable<decimal> Temperature1 { get; set; }
        public Nullable<decimal> Temperature2 { get; set; }
        public Nullable<decimal> Temperature3 { get; set; }
        public Nullable<decimal> TemperatureAvg { get; set; }
        public Nullable<System.DateTime> MeasureDate { get; set; }
        public Nullable<bool> DeleteFlg { get; set; }
    }
}
