using semigura.Commons;
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace semigura.DBContext.Models
{

    public partial class MediaModel
    {
        public string Id { get; set; }
        public string Path { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Type { get; set; }
        public string TerminalId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedOnUnixTimeStamp
        {
            get
            {
                return CreatedOn.HasValue ? Utils.DateTimeToLongTimeString(CreatedOn) : null;
            }
        }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedById { get; set; }
        public string LotContainerId { get; set; }

    }
}
